foodDelivery/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

foodDelivery/foodDelivery/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('item/', include('items.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foodDelivery/items/urls.py
from django.urls import path
from . import views
app_name = 'items'

urlpatterns = [
    path('<int:pk>/', views.detail, name='detail'),
    path('order/<int:pk>', views.order, name='order'),
    path('view_order/', views.view_order,name='view_order')
]

foodDelivery/core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

# class User(AbstractUser):
#     SELLER = 1
#     CUSTOMER = 2

#     ROLE_CHOICES = (
#         (SELLER,'Seller'),
#         (CUSTOMER, 'Customer'),
#     )
#     role = models.PositiveSmallIntegerField(choices=ROLE_CHOICES, blank=True, null=True)

foodDelivery/items/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=255) 
    class Meta:
        ordering = ('name',)
        verbose_name_plural = "Categories"

    def __str__(self) -> str:
        return self.name
    
class Item(models.Model):
    category = models.ForeignKey(Category, related_name='item', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_image', null=True, blank=True)
    sold_out = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='item', on_delete=models.CASCADE)


    def __str__(self) -> str:
        return self.name
    
class Order(models.Model):
    item = models.ForeignKey(Item, related_name='item', on_delete=models.CASCADE)
    buyer = models.ForeignKey(User, related_name='buyer', on_delete=models.CASCADE)
    seller = models.ForeignKey(User, related_name='seller', on_delete=models.CASCADE)
    finished_order = models.BooleanField(default=False)
    purchase_time = models.DateTimeField(auto_now_add=True)
    def __str__(self) -> str:
        return self.item.name
    
    

foodDelivery/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

foodDelivery/core/views.py
from django.shortcuts import render,redirect
from .forms import LoginForm, SignupForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from items.models import Item, Category
def index(request):
    items = Item.objects.filter(sold_out=False)[0:6]
    categories = Category.objects.all()
    return render(request, 'core/index.html', {
        'items': items,
        'cateogories' : categories,
    })

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SignupForm()
    
    return render(request, 'core/signup.html', {
        'form' : form,
    })

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, 'Login successful!')
            return redirect('/')
        else:
            form = LoginForm()
            messages.warning(request, 'Your username or password is incorrect. Please try again.')
        
    else:
        form = LoginForm
        
    return render(request, 'core/login.html', {
            'form': form,
        })

def logout_view(request):
    logout(request)
    return redirect('/')

foodDelivery/items/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Item, Order
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib import messages
# Create your views here.
def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    return render(request, 'items/detail.html', {
        'item' : item
    })

@login_required
def order(request, pk):
    item = get_object_or_404(Item, pk=pk)
    buyer = request.user
    seller = item.created_by
    order = Order(item=item, seller=seller, buyer=buyer)
    order.save()
    messages.success(request, 'Your food is now in preparation. Please patiently wait.')
    return redirect('/')

def view_order(request):
    orders_made = Order.objects.filter(buyer=request.user)[0:6]
    return render(request, 'items/order.html', {
        'orders_made': orders_made,
    })

foodDelivery/core/templates/core/base.html
{% load item_extras %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title %}{% endblock %} | foodChaser</title>
</head>


<body>
    <nav class="px-6 py-6 flex justify-between items-center border-b border-gray-200">
        <a href="{% url 'core:index' %}" class="text-xl font-semibold">Food Delivery</a>
        <div class="space-x-6">
            <a href="{% url 'items:view_order' %}" class="text-lg font-semibold">Order</a>
            <a href="*" class="text-lg font-semibold">Basket</a>
            {% if request.user.is_authenticated%}
                {% if request.user|is_seller:"seller" %}
                    <a href="*" class="text-lg font-semibold">Edit Item</a>
                {% else %}
                {% endif %}
                <a href="*" class="rounded-xl bg-teal-500 px-6 py-4 font-semibold text-lg text-white hover:bg-teal-700">Dashboard</a>
                <a href="{% url 'core:logout' %}" class="rounded-xl bg-teal-500 px-6 py-4 font-semibold text-lg text-white hover:bg-teal-700">Log Out</a>
            {% else %}
                <a href="{% url 'core:signup' %}" class="rounded-xl bg-teal-500 px-6 py-4 font-semibold text-lg text-white hover:bg-teal-700">Sign Up</a>
                <a href="{% url 'core:login' %}" class="rounded-xl bg-teal-500 px-6 py-4 font-semibold text-lg text-white hover:bg-teal-700">Log in</a>
            {% endif %}
        </div>
    </nav>
    <!-- {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %} -->
    <div class="py-4 px-4 w-full bg-teal-400">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    </div>
   
    {% block content %}
    {% endblock %}
</body>
</html>

foodDelivery/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Index{% endblock %}

{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Newest Item</h2>
    <div class="grid grid-cols-4 gap-2">
        {% for item in items %}
            <a href="{% url 'items:detail' item.id %}">
                <div>
                    <img src="{{ item.image.url }}" class="rounded-t-xl">
                </div>
                <div class="p-6 bg-white rounded-b-xl">
                    <h2 class="text-xl font-semibold">{{ item.name }}</h2>
                    <p class="text-gray-500">Prices: {{ item.price }}</p>
                </div>
            </a> 
        {% endfor %}
        <div>

        </div>
    </div>
</div>

{% endblock %}

foodDelivery/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Login</h1>

    <form method="post" action=".">
        {% csrf_token %}
        <div class="mb-3">
            <label class="inline-block mb-2">Username</label>
            {{ form.username }}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Password</label>
            {{ form.password }}
        </div>

        <button class="py-4 px-8 text-lg bg-teal-500 rounded-xl text-white hover:bg-teal-700">Login</button>
    </form>
</div>
{% endblock %}

foodDelivery/core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Signup{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>

    <form method="post" action=".">
        {% csrf_token %}
        <div class="mb-3">
            <label class="inline-block mb-2">Username</label>
            {{ form.username }}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Email</label>
            {{ form.email }}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Password</label>
            {{ form.password1 }}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Repeat Password</label>
            {{ form.password2 }}
        </div>

        <button class="py-4 px-8 text-lg bg-teal-500 rounded-xl text-white hover:bg-teal-700">Submit</button>
    </form>
</div>
{% endblock %}

foodDelivery/items/templates/items/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ item.name }}{% endblock %}

{% block content %}
    <div class="grid grid-cols-2 gap-4">
        <div class="col-span-1">
            <img src="{{ item.image.url }}">
        </div>
        <div class="col-span-1">
            <h1 class="inline-block font-semibold">{{ item.name }}</h1>
            <p class="text-gray-500"><strong>Prices:</strong>{{item.price}}</p>
            <p class="text-gray-500"><strong>Seller:</strong>{{item.created_by.username}}</p>
            {% if item.description %}
            <p class="text-gray-700">
                <strong class="text-gray-500">Description:</strong>
                {{ item.description }}
            </p>
            {% endif %}
            {% if user.is_authenticated %}
                <a href="{% url 'items:order' item.id %}">
                    <button class="py-4 px-8 text-lg bg-teal-500 rounded-xl text-white font-semibold hover:bg-teal-700">Order</button>
                </a>
            {% endif %}
        </div>

    </div>
{% endblock %}

foodDelivery/items/templates/items/order.html
{% extends 'core/base.html' %}

{% block title %}Your Order{% endblock %}

{% block content %}
    {% for order in orders_made %}
        <div class="flex bg-green-100 rounded-xl m-4">
            <div class="pr-6">
                <img src="{{ item.image.url }}">
            </div>
            <div>
                <p class="mt-4"><strong>{{ order.item.name }}</strong></p>
                <p><strong>Seller:</strong>{{ order.seller.username }}</p>
                <p><strong>Purchase time:</strong></p>
                <p><strong class="mb-4">Predicted arriving time:</strong></p>
            </div>
            
            
        </div>
    {% endfor %}
{% endblock %}